steps:
  - id: Job A_01
    name: ubuntu:20.04
    entrypoint: bash
    args:
      - -c
      - |
        touch job_A_01.txt
        ls -l
  - id: Job A_02
    name: ubuntu:20.04
    entrypoint: bash
    args:
      - -c
      - |
        touch job_A_02.txt
        ls -l
  - id: Job A_03
    name: ubuntu:20.04
    entrypoint: bash
    args:
      - -c
      - |
        touch job_A_03.txt
        ls -l

  - id: Job B_01
    name: ubuntu:20.04
    entrypoint: bash
    args:
      - -c
      - |
        touch job_B_01.txt
        ls -l
    waitFor: ['-']
  - id: Job B_02
    name: ubuntu:20.04
    entrypoint: bash
    args:
      - -c
      - |
        touch job_B_02.txt
        ls -l
  - id: Job B_03
    name: ubuntu:20.04
    entrypoint: bash
    args:
      - -c
      - |
        touch job_B_03.txt
        ls -l

  - id: Job C_01
    name: ubuntu:20.04
    entrypoint: bash
    args:
      - -c
      - |
        touch job_C_01.txt
        ls -l
    waitFor: ['-']
  - id: Job C_02
    name: ubuntu:20.04
    entrypoint: bash
    args:
      - -c
      - |
        touch job_C_02.txt
        ls -l
  - id: Job C_03
    name: ubuntu:20.04
    entrypoint: bash
    args:
      - -c
      - |
        touch job_C_03.txt
        ls -l

  - id: Job Last
    name: ubuntu:20.04
    entrypoint: bash
    args:
      - -c
      - |
        ls -l
    waitFor:
      - Job A_03
      - Job B_03
      - Job C_03

  - id: Show environment variables
    name: ubuntu:20.04
    entrypoint: bash
    args:
      - -c
      - |
        echo "=> Environment Variables"
        echo PROJECT_ID:     $PROJECT_ID
        echo BUILD_ID:       $BUILD_ID
        echo COMMIT_SHA:     $COMMIT_SHA
        echo REVISION_ID:    $REVISION_ID
        echo SHORT_SHA:      $SHORT_SHA
        echo REPO_NAME:      $REPO_NAME
        echo BRANCH_NAME:    $BRANCH_NAME
        echo TAG_NAME:       $TAG_NAME
        echo _HEAD_BRANCH:   $_HEAD_BRANCH
        echo _BASE_BRANCH:   $_BASE_BRANCH
        echo _HEAD_REPO_URL: $_HEAD_REPO_URL
        echo _PR_NUMBER:     $_PR_NUMBER
    waitFor: ['-']

options:
  env:
    - 'PROJECT_ID=$PROJECT_ID'
    - 'BUILD_ID=$BUILD_ID'
    - 'COMMIT_SHA=$COMMIT_SHA'
    - 'REVISION_ID=$REVISION_ID'
    - 'SHORT_SHA=$SHORT_SHA'
    - 'REPO_NAME=$REPO_NAME'
    - 'BRANCH_NAME=$BRANCH_NAME'
    - 'TAG_NAME=$TAG_NAME'
    - 'GITHUB_TOKEN=$_GITHUB_TOKEN'
    - '_PR_NUMBER=$_PR_NUMBER'
